name: Step 1, Master Basic Search Syntax

# This step triggers when any comment is created on an issue
# This workflow updates from step 1 to step 2

on:
  workflow_dispatch:
  issue_comment:
    types:
      - created

permissions:
  contents: write
  issues: write  # Needed to create issues via REST API

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_any_comment_created:
    name: On any issue comment
    needs: get_current_step

    # Run only if:
    # 1. This repository isn't a template
    # 2. The step is currently 1
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 1 }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create sample issues using REST API
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/issues \
               -d '{"title":"Bug: Navigation breaks on mobile","body":"When using the app on mobile devices, the navigation menu doesn’t work properly.","labels":["bug"]}'

          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/issues \
               -d '{"title":"Feature request: Dark mode","body":"Would be great to have a dark mode option for the interface.","labels":["enhancement"]}'

          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/issues \
               -d '{"title":"Documentation needs updating","body":"The API documentation is outdated and needs to be updated.","labels":["documentation"]}'
      
      - name: Update to step 2
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2


