name: Step 3, Manage Issue Subscriptions

# This step triggers when a comment containing "subscribed" is posted on an issue
# This workflow updates from step 3 to step 4

on:
  workflow_dispatch:
  issue_comment:
    types:
      - created

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_subscribed_comment:
    name: On subscribed comment
    needs: get_current_step

    # Run only if:
    # 1. Repo is not a template
    # 2. Current step is 3
    # 3. Comment contains "subscribed"
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 3
          && contains(github.event.comment.body, 'subscribed') }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update to step 4
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4

